service: deffillama

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

package:
  exclude:
    - '**/*'
  include:
    - '*.py'

functions:
  deffiingest:
    handler: handler.hello
